# Generated by Django 3.2.8 on 2021-10-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='number_songs',
        ),
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='surname',
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='HIII', max_length=30),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
