# Generated by Django 3.2.8 on 2021-10-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20211027_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
