# Generated by Django 3.2.8 on 2021-10-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='number_songs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='surname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
