# Generated by Django 3.2.8 on 2021-10-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20211027_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='number_songs',
            field=models.IntegerField(default=1),
        ),
    ]
