# Generated by Django 3.2.8 on 2021-10-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_song_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artist'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='Artist',
        ),
        migrations.AlterModelTable(
            name='song',
            table='Song',
        ),
    ]
