# Generated by Django 3.2.8 on 2021-11-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20211108_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.CharField(default='Unverified', max_length=30),
        ),
    ]
