# Generated by Django 3.2.8 on 2021-11-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_artist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='status',
            field=models.CharField(choices=[('u', 'Unverified'), ('v', 'Verified')], max_length=30),
        ),
    ]
