# Generated by Django 3.2.8 on 2021-11-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(db_table='reference_table', to='student.Teacher'),
        ),
    ]
